services:
  postgres:
    image: postgres:16
    container_name: oto-postgres-storage
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
        - oto-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: oto-postgres-dashboard
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
        - oto-network

  temporal:
    container_name: oto-temporal-server
    image: temporalio/auto-setup:latest
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=${POSTGRES_SEED}
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    depends_on:
        - postgres
    networks:
        - oto-network
    ports:
      - "7233:7233"

  temporal-ui:
    container_name: oto-temporal-ui
    image: temporalio/ui:latest
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    depends_on:
      - temporal
    networks:
        - oto-network

  atlas-migration:
    image: arigaio/atlas:latest
    container_name: oto-atlas-migration
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    command: >
      migrate apply
      --dir file://migrations --url postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    volumes:
      - ./migrations:/migrations
    networks:
      - oto-network

  oto-api:
    container_name: oto-service-api
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    image: oto-api
    ports:
      - "1515:1515"
    networks:
      - oto-network
    restart: unless-stopped

  oto-web:
    container_name: oto-service-web
    build:
      context: .
      dockerfile: cmd/web/Dockerfile
    image: oto-web
    ports:
      - "2929:2929"
    networks:
      - oto-network
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin_data:

networks:
    oto-network:
        driver: bridge
